CREATE TYPE "DateFormat" AS ENUM ('MM_DD_YYYY', 'DD_MM_YYYY', 'YYYY_MM_DD');

ALTER TABLE "Tenant"
ADD COLUMN "dateFormat" "DateFormat" NOT NULL DEFAULT 'MM_DD_YYYY',
ADD COLUMN "timezone" TEXT NOT NULL DEFAULT 'UTC';
