import { ApiProperty } from '@nestjs/swagger';
import { IsString, Matches } from 'class-validator';

export const WIDGET_KEY_PATTERN = /^wgt_[A-Za-z0-9_-]{43}$/;

export class CreateWebVoiceSessionDto {
  @ApiProperty({
    example: 'wgt_0123456789abcdefghijklmnopqrstuvwxyzABCDEFG',
    description: 'Opaque public routing identifier generated by the server.',
  })
  @IsString()
  @Matches(WIDGET_KEY_PATTERN, { message: 'widgetKey has an invalid format.' })
  widgetKey!: string;
}
